### PR TITLE
Support newly released Laravel 5.7

### PR DESCRIPTION
**Pull request by richardkeep**

### CODE REVIEW

**Comment by luceos** [comment]
If I'm not mistaken we can safely modify the constraint to be `^5.6.0` this would allow any future 5.x version?

**Comment by fletch3555** [comment]
Yes, `^5.6.0` should be fine (and would allow `5.6.1`, `5.6.84`, `5.7.0`, `5.8.0`, etc).  The issue with this PR is that changing `5.6.0` to `5.7.0` removes support for 5.6, which is still widely used.

**Comment by dbrw** [comment]
no release with this patch, yet?

**Comment by richardkeep** [comment]
yep. :(

**Comment by luceos** [comment]
@dbrw I'm working on it, there's just a minor change needed and I want to patch the tests before tagging a new version 👍

**Pull request closed without merging**
