### PR TITLE
Change MariaDB generator to be more generic (to support 10.4)

### LINKED ISSUE #826: General error: 1348 Column 'Password' is not updatable
__Description__

As described on the website:
https://mariadb.com/kb/en/library/mysqlglobal_priv-table/
"The mysql.global_priv table was introduced in MariaDB 10.4.1 to replace the mysql.user table."

Because of that I get an error "General error: 1348 Column 'Password' is not updatable" when I want to use the command tenancy: key:update

---

__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.8
- database driver and version: mariadb 10.4.6
- php version: 7.3

---

__Error log__

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1348 Column 'Password' is not updatable")
      /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119

  2   PDOException::("SQLSTATE[HY000]: General error: 1348 Column 'Password' is not updatable")
      /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

```

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #826 ... but reverts (some of) the pre-10.4 stuff introduced in 5.4.0 via https://github.com/tenancy/multi-tenant/commit/44858ed28f9a1dac3718ea6863c79f897c464999#diff-e51e809604145f74d16f6f072f6f9976

### CODE REVIEW

**Comment by drbyte** [comment]
Notes:
The first commit in this PR ran CI against MariaDB 10.3, and tests passed.
The second commit ran CI against MariaDB 10.4, and tests passed.

**Review by fletch3555 — APPROVED** [review]

**Comment by Plytas** [comment]
Will this work with older MariaDB versions?

**Comment by drbyte** [comment]
> Will this work with older MariaDB versions?

As I posted above, the tests on CircleCI pass on 10.3.
That's all I know for certain.

**Comment by luceos** [comment]
Thanks @drbyte this cleans it up nicely as well 👏

**Pull request merged**
