### PR TITLE
add support for multiple tenant migration path

### LINKED ISSUE #598: multiple tenant migration path
it will be very great if we can do something like this

``` 
"tenant-migrations-path" => [
database_path('migrations/tenant1'), database_path('migrations/tenant2')
]
```

instead of just single path
```
"tenant-migrations-path" => database_path('migrations/tenant'),
```

### PR DESCRIPTION
**Pull request by vortechron**
fixes #598

### CODE REVIEW

**Comment by johannesschobel** [comment]
i thought using wildcards, e.g., `/database/migrations/tenants/*` would work "out of the box" right now..

**Comment by vortechron** [comment]
see https://github.com/hyn/multi-tenant/issues/598#issuecomment-418722317

**Comment by vortechron** [comment]
this pr cause an error when running `php artisan migrate` command, i will make another pr

**Comment by luceos** [comment]
@vortechron did you abandon your efforts?

**Pull request closed without merging**
