### PR TITLE
Update domain in nginx vhost template

### PR DESCRIPTION
**Pull request by stancl**

### CODE REVIEW

**Comment by ArlonAntonius** [comment]
While you're at it, could you also edit the one for Apache? 2 in 1 combo :)
After that, I'm fine with merging this.

**Comment by stancl** [comment]
Done :)

**Comment by ArlonAntonius** [comment]
Sorry to do this to you, but can you also update the hyn/multi-tenant to tenancy/multi-tenant? 😂

**Comment by drbyte** [comment]
@ArlonAntonius maybe you're just courteously offering the PR contributor the opportunity to do the changes, but did you know you can click the Edit option in the Files Changed tab and edit the PR directly? Your changes get added as another commit, and then you can merge both their and your code in the same PR, without having to wait for additional contributions. 
Things like these small updates that are more the Maintainer's domain make sense for that IMO.
(Things like totally changing the way the PR was done probably warrant asking the contributor to do more work.)
Just tossing it in in case you haven't seen that feature in Github.

**Comment by ArlonAntonius** [comment]
Hi @drbyte,

I feel like Stan has done quite a bit for the community, and want to let that appear in the statistics a bit more as well.
He has helped a lot of people on our Discord server so I'd really like to give him these few extra changes so he will show up earlier in the contributor list as well :) 

I am aware of the feature and might do the changes myself next time.

**Comment by ArlonAntonius** [comment]
Thanks for the work @stancl great job like always, keep up the good work :D

**Comment by drbyte** [comment]
> I feel like Stan has done quite a bit for the community, and want to let that appear in the statistics a bit more as well.
> He has helped a lot of people on our Discord server so I'd really like to give him these few extra changes so he will show up earlier in the contributor list as well :)

I completely agree!

**Pull request merged**
