### PR TITLE
[5.x] Laravel 10 Support

### PR DESCRIPTION
**Pull request by ArlonAntonius**

### CODE REVIEW

**Review by bkintanar — APPROVED** [review]
LGTM.

**Comment by jonquintero** [comment]
Hi guys  how are you.
Any  new change about this update?
Thanks

**Comment by PouleR** [comment]
Are you planning to merge this PR so we can update to Laravel 10? Thank you in advance!

**Comment by PouleR** [comment]
@ArlonAntonius please note that the usage of the $dates property has been removed.
This is still being used in the Hostname model: `protected $dates = ['under_maintenance_since'];` and should be rewritten to the casts property:

src/Models/Hostname.php:
```
protected $casts = [
    'under_maintenance_since' => 'datetime',
];
```

**Comment by mattvb91** [comment]
any update on this?

**Comment by PouleR** [comment]
@ArlonAntonius I've create a PR for you to update this pull request, this should fix the build so we can hopefully merge this.

**Comment by jonquintero** [comment]
Hi @PouleR Can you make this works with php 8.2 too ? Thanks

**Comment by PouleR** [comment]
> Hi @PouleR Can you make this works with php 8.2 too ? Thanks

@jonquintero I just added php-8.2 to the circle ci jobs!

**Comment by jonquintero** [comment]
Hi guys, how are you? I want to ask if there is any news about this ?

**Comment by PouleR** [comment]
@ArlonAntonius how about merging this PR? Would be really appreciated!

**Comment by ArlonAntonius** [comment]
You're a hero @PouleR, thanks for all the effort 🚀

**Comment by mattvb91** [comment]
Thanks @PouleR. Could we also get a tag so we can pull it?

**Comment by tvbeek** [comment]
@PouleR @ArlonAntonius I'm not sure if you think about this, but this creates a breaking change in a minor release. That is because you drop Laravel 9 support.

Is that intended? Or does there need to be a new PR that bring back the support for Laravel 9.

**Comment by ArlonAntonius** [comment]
@tvbeek You are completely right, that is a user error and it should be made backward-compatIble. I should have some time this weekend to fix that.
Only thing I am worried about is the PHP versions.

**Comment by jonquintero** [comment]
Is not possible to put a tag for laravel 10 support for example 5.9.1 while for laravel 9 you would use something like 5.9.0 ?

**Comment by tvbeek** [comment]
@jonquintero I'm interested how you see that working for new tags? A 5.10.1 for Laravel 10 and 5.10.0 for Laravel 9? And besides that it is still a breaking change 😃

**Comment by ArlonAntonius** [comment]
@tvbeek is right, it is a breaking change and should not have been. I have a PR ready in order to add back L9 compatibility. If you guys have ideas, let's move it there :) #1041

**Pull request merged**
