### PR TITLE
#534 - Adding TenantAwareConnection Trait

### PR DESCRIPTION
**Pull request by adamthomason**
Adding a trait which can be added to models in order dynamically choose the connection based on the current hostname, as reference in #534.

### CODE REVIEW

**Comment by luceos** [comment]
A PR requires tests before it can be merged. Let me know if you're up for it, otherwise I'll patch it up once I get to it..

**Comment by adamthomason** [comment]
I'm happy to do this myself - I'll get around to it at some point today or tomorrow!

**Comment by luceos** [comment]
Feel free to look at the existing mock models I've used for both System and Tenant aware traits.

Let me know if you need any assistance!

**Comment by adamthomason** [comment]
Hi @luceos, I've had a busy week and am now on vacation for 2 weeks. If you'd like to look at this yourself to get this in, then I'm more than happy for you to add tests :)

**Comment by mintunitish** [comment]
Are the tests done or is it still pending?

**Comment by adamthomason** [comment]
This is still pending I'm afraid, but please feel free if you'd like to tackle them!

**Pull request merged**
