### PR TITLE
Fix problems with laravel 9 

### PR DESCRIPTION
**Pull request by fabmade**
Laravel 9 has a new version the filesystem "flysystem". That is not compatible with the tenancy/multi-tenant package.
I fixed the problems with that change.

### CODE REVIEW

**Comment by markieo1** [comment]
@fabmade Could you please fix the tests, so this PR could be reviewed?

**Comment by fabmade** [comment]
@markieo1 the tests should be fixed now

**Comment by Ruud-Gerrits** [comment]
Any idea on when this will be merged?

**Comment by bkintanar** [comment]
I'll review it this weekend. It's already night here.

**Comment by markieo1** [comment]
@bkintanar Any progress?

**Comment by bkintanar** [comment]
merged and tagged.

**Pull request merged**
