### PR TITLE
Laravel 5.4

### PR DESCRIPTION
**Pull request by Diddyy**
@MithrandirDK hope you don't mind, submitted for review to see if compatible.
@Luceos Tested on a local environment, everything is perfect. Haven't spotted any issues and I believe that https://github.com/MithrandirDK/multi-tenant/commit/586f824a62ee52077ff6962aed317f710fc7753f makes good use of the cache.

### CODE REVIEW

**Comment by Diddyy** [comment]
Checks are failing due to tests not being updated to run with Laravel 5,4, they are failing as it is still using 5.3
I would fork the branch and edit it but I want to keep full credit to @MithrandirDK

**Comment by luceos** [comment]
@Diddyy thanks for the PR. I will take a look asap. Tests have to work in order to merge, but I can probably take care of that.

**Comment by luceos** [comment]
So the first comment I have is that you replace 5.3 with 5.4, tagging this will drop backward compatibility. I should merge this in a separate branch that supports 5.4.

**Comment by MithrandirDK** [comment]
I don't mind at all - in fact, if you want to do a fork to keep it clean, I'd say go for it. I can live with less than full credit :)

Do note that I have used it as a general fork for things, I need in my setup, so forcing to HTTPS and using a different database for PHPUnit/testing environments may not be universally applicable.

**Comment by luceos** [comment]
@Diddyy I have decided not to verify whether this can work and will not merge it in. Here are the reasons:

- 3.x is progressing nicely and will support 5.3, 5.4 and dev-master, once 5.5 comes out dev-master will once again be made compatible. This way of working allows me to create a more future proof version of the package.
- As said in the comments, merging will drop the support for 5.3. You should probably have set the constraint to `5.3.* || 5.4.*` and then patch up the version to work. Not simply delete the console commands.
- I'm not interested in supporting version 2.x much longer than needed. There are a lot of drawbacks in how it's been set up that limited the flexibility of configuring your specific environment. Version 3.x is being written to be more extendable and flexible all over.
- Tests fail.

**Pull request closed without merging**
