### PR TITLE
Fix Queue Provider & clean code with helpers

### PR DESCRIPTION
**Pull request by ArlonAntonius**
#728 after an investigation by the hero without a cape @bastien-phi, the exact issue was found and we have a potential fix.

### CODE REVIEW

**Comment by Dmarch28** [comment]
Cleaver very and a nice idea!

**Comment by 100023330613886** [comment]
Please

**Comment by 100023330613886** [comment]
https://github.com/hyn/multi-tenant/pull/749#issuecomment-474397884

**Comment by 100023330613886** [comment]
Facebook longin please

**Pull request merged**
