### PR TITLE
General approach to CLI/Artisan

### PR DESCRIPTION
**Pull request by MithrandirDK**
This is my suggestion for a single artisan command that can delegate execution of another command on each (or selected) tenants

### CODE REVIEW

**Comment by luceos** [comment]
Looking good, will wait for vital checks to finish.

**Comment by MithrandirDK** [comment]
If you can figure out, what is wrong with https://styleci.io/analyses/zRA6L7

to me, it looks like it wants me to replace a { with a { - doesn't make much sense

**Comment by bkintanar** [comment]
@MithrandirDK I think that's a new line at the end of file.

**Comment by luceos** [comment]
Thanks it's fine, StyleCI patches the oddities when necessary I've modified its settings to do so.

**Comment by MithrandirDK** [comment]
And I added the newline, too :)

**Comment by luceos** [comment]
Closes #157

**Pull request merged**
