### PR TITLE
Update QueueProvider.php

### LINKED ISSUE #855: Laravel Vapor SQS queue payload "attempts" missing
__Description__

When a queued job throws an exception, Laravel Vapor tries to update a vapor-specific `attempts` key in the payload that seems to have been removed. After contacting the Laravel Vapor team for help, we were told that it is likely that someone has removed the custom keys that https://github.com/laravel/vapor-core adds to jobs. After doing some investigation, there isn't anything else that might have touched the payload accept this package, so I wanted to find some help if anyone might be able to figure out what might be happening.

Laravel Vapor assigns the payload keys here: https://github.com/laravel/vapor-core/blob/9a486ab614e92c01cbd2d089b01cc0124c8eff0a/src/Queue/VaporQueue.php#L41

This package modifies the payload here: https://github.com/tenancy/multi-tenant/blob/5.x/src/Providers/Tenants/QueueProvider.php#L29

I don't really know how the `createPayloadUsing` or the `createPayloadArray` methods work, so I'm a bit stuck in figuring out where to look. 

---

__Actual behavior__

When a job throws an exception on an app that's powered by Laravel Vapor, the job should recognise that it's failed, but the `attempts` key in the job payload is missing, possibly due to multi-tenant's queue provider.

__Expected behavior__

Additional keys added to a job payload should not be removed.

---
__Information__

- hyn/multi-tenant version: 5.5.0
- laravel version: 6.2.0
- database driver and version: MySQL 8.0
- webserver software and version: Laravel Vapor
- php version: 7.3? Not sure exact version Vapor is running, but minimum

---

__Error log__

```text
vendor/laravel/vapor-core/src/Queue/VaporJob.php:21
Undefined index: attempts
```

I understand that there currently is no expectation for this package to work with Laravel Vapor, but would love to pick on the community's brain on how I may potentially resolve this.

Thanks in advance!

### PR DESCRIPTION
**Pull request by jedimdan**
Attempt to fix #855 by matching the queue provider to the one that's in T/T (https://github.com/tenancy/tenancy/blob/df308639405d5d2c29abf08fea8bec8d28321484/src/Identification/Queue/Providers/IdentificationProvider.php)

### CODE REVIEW

**Comment by jedimdan** [comment]
This is my first PR to this package, so I'm not really sure how to trigger the CI tests to run.

**Comment by bkintanar** [comment]
@ArlonAntonius can you check on this personally?

**Comment by jedimdan** [comment]
I just got the CI results in my email (it failed). Will continue working on this PR

**Comment by jedimdan** [comment]
I’ll try to test this fix against a real Laravel Vapor environment too.

**Comment by ArlonAntonius** [comment]
@bkintanar Seems fine to me.
As long as @jedimdan tests this in Vapor so he's sure it works. If he's sure of that and removes the WIP tag, we can see how our tests are with this :)

**Comment by jedimdan** [comment]
My apologies, I haven't gotten down to do it yet. Will let you know once I do!

**Comment by jedimdan** [comment]
This took a while as I had to find time to upgrade my test project to Laravel 7. Unfortunately, I'm still seeing the same error on Vapor. For reference, here's the project I have deployed to Vapor: https://github.com/jedimdan/vapor-tenancy-queue-test. Visiting `/` will dispatch a job that will throw an exception. However, telescope shows that the exception is a vapor error not able to find the `attempts` key.

**Comment by jedimdan** [comment]
@bkintanar @ArlonAntonius any advice on what else we can try? Do you think it's an issue with the fix I'm attempting?

**Comment by sniper7kills** [comment]
@jedimdan made a pull request on your fork.... Should resolve the issue.

**Comment by jedimdan** [comment]
@sniper7kills thanks! that worked!! 

image

**Comment by bkintanar** [comment]
@jedimdan can you remove the WIP tag so that we can merge this?

**Comment by jedimdan** [comment]
I've removed the WIP tag. I'm still seeing failed tests on CircleCI though

**Comment by bkintanar** [comment]
@jedimdan still having CircleCI error?

**Comment by jedimdan** [comment]
@bkintanar Oh looks like it passed! Sorry I didn't know I wouldn't receive any notification if the CI passed so I assumed it failed as the previous one had failed. https://app.circleci.com/pipelines/github/tenancy/multi-tenant/6/workflows/568f19bd-85b7-4f0f-8e39-8ee7a977c7fa

**Comment by bkintanar** [comment]
Thanks @jedimdan. @ArlonAntonius I'll merge this if you don't have any objections.

**Review by bkintanar — APPROVED** [review]

**Comment by Stenfrank** [comment]
I have the same error but only for when it runs in production

```php
composer install --optimize-autoloader --no-dev
```

**Pull request merged**
