### PR TITLE
Trim slashes from request uri before redirecting

### PR DESCRIPTION
**Pull request by JaZo**

### CODE REVIEW

**Comment by ArlonAntonius** [comment]
Hi @JaZo,

Could you specify what problems you are bumping into in this case? This looks like an adjustment for a really specific situation and looks like something that might be adjustable with some server configuration.

**Review by sniper7kills — APPROVED** [review]
Approved after internal review.

**Comment by bkintanar** [comment]
Approved after internal review.

**Comment by JaZo** [comment]
Thanks for the quick response!

**Pull request merged**
