### PR TITLE
Remove APP_KEY dependency for password generation

### PR DESCRIPTION
**Pull request by ghost**
This PR removes the `APP_KEY` from the password hashing.

The hash is generated through the following website properties:

- ID
- UUID
- Created at timestamp

All these parameters should never change in the application lifetime and provide a relative unique combination.

Changing the `APP_KEY` used to brick the application. With this PR you are able to rotate the `APP_KEY` as needed. Official recommendations for changing the `APP_KEY` in the past have also appeared: https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30

Resolved issues: https://github.com/hyn/multi-tenant/issues/574

### CODE REVIEW

**Comment by luceos** [comment]
We need a way to migrate existing installs. Otherwise merging this PR will disrupt production environments after blind upgrades. Hence being reluctant.

**Comment by ghost** [comment]
@luceos I agree, that's why I think we should label this as a BC. Since changing the APP_KEY would have the same impact (and has probably already disrupted some environments), we are on a better path with this implementation.

Any ideas how a good migration process could be established? My suggestion would simply be an incompatible release without any migration.

**Comment by twdnhfr** [comment]
Wouldn't it be better to just remove the need for a password for the tenant connection? As far as I can see the app_key is only used to have something random while creating but afterwards static. The tentant connection password isn't known to the "user" and is re-generated on each use. So you could create the mysql user without a password when connecting from localhost.

Or maybe as an alternative: using the .env for the tenant connection credentials just like the regular db connection

**Comment by luceos** [comment]
> The tentant connection password isn't known to the "user" and is re-generated on each use.

The password is not re-generated and not using a password is very unsafe.

> Any ideas how a good migration process could be established? My suggestion would simply be an incompatible release without any migration.

Not having a migration plan is unacceptable. I think the best thing to do is write a migration command that updates users one at a time, this requires keeping knowledge about the old method as well.

**Comment by twdnhfr** [comment]
So just being curious, where do you store the password for the tenant connection?

**Comment by ghost** [comment]
> Not having a migration plan is unacceptable. I think the best thing to do is write a migration command that updates users one at a time, this requires keeping knowledge about the old method as well.

I understand, but using the `APP_KEY` is also unacceptable.

Do you have any ideas how that migration command could look like?

**Comment by fletch3555** [comment]
> So just being curious, where do you store the password for the tenant connection?

We don't.  It's recalculated in code for each run, but not changed in the database.  E.g., if you know how to generate it (and have all the appropriate information), you would be able to log in manually at any point

**Comment by luceos** [comment]
> Do you have any ideas how that migration command could look like?

Yes the command would resolve the Connection class of this package from IoC for each Tenant website. This connection class has a refactored method for the new configuration. A connection would be set up with the system connection of the tenant website (managed by property) by using the Connection class system() method, after which it updates the user password. This last step would require new methods on the existing Database Generator Drivers.

**Comment by ghost** [comment]
> Yes the command would resolve the Connection class of this package from IoC for each Tenant website. This connection class has a refactored method for the new configuration. A connection would be set up with the system connection of the tenant website (managed by property) by using the Connection class system() method, after which it updates the user password. This last step would require new methods on the existing Database Generator Drivers.

Sounds good! You're more familiar with the codebase, can you add that command? :-)

**Comment by luceos** [comment]
In hindsight I think generating this tenant password should have at least one element in the hasher string that is not available in the system database. As such it would be better to start using a custom TENANCY_KEY value in the future..

**Comment by ghost** [comment]
> In hindsight I think generating this tenant password should have at least one element in the hasher string that is not available in the system database. As such it would be better to start using a custom TENANCY_KEY value in the future..

Not a good idea, this introduces the necessity of storing a permanent password. For what? Just to achieve the same result that the provided values of this PR also offer.

**Comment by luceos** [comment]
All three values being used in this PR are part of the system database. Thus when the system database is breached, all tenants are exposed. I'd rather not introduce something that risky.

**Comment by ghost** [comment]
@luceos so when the system database is breached, your solution provides more security? There is a big lack of realism here.

**Comment by luceos** [comment]
> There is a big lack of realism here.

Care to explain @phpduck?

I am aware the system connection (per default) is supposed to have access to its tenants, but this is not a necessity. Lesser permissions to the system user (while stilling allowing it to create other databases and users) are still a feasibility. So I'd love to hear why my perspective is lacking realism.

**Comment by ghost** [comment]
@luceos sure, these concerns are not within the scope of this package. Managing DB user permissions are done on another level, this makes your complete argument just invalid. And if your system db is breached, how can you guarantee that no access is provided to tenants with your key solution? That makes no difference to the other unique values. The system DB should be protected on a whole other level.

**Comment by luceos** [comment]
The benefit of having one segment of the hashing outside of the system database is the ability to store it outside of harms way. Even though people with bad intent possibly gained access to the system database by checking the database.php or the .env aka the filesystem, this is not the only way to inject environment variables into an app. Another common approach is to use machine environment variables, eg when building docker images. And even though these might be read as well from the filesystem, when having gained access, other key stores like hashicorps vault aren't that easily accessible.

**Comment by ghost** [comment]
@luceos that is way too specific, I prefer the more general approach here. However, if this PR doesn't suit the maintainers, it can be rejected/modified or whatever. IMHO the `APP_KEY` dependency is still a pain point which should be handled somehow.

**Comment by Plytas** [comment]
I agree with both sides.
Tenancy should not depend on `APP_KEY` as it **needs** to be able and **should** rotate. Extra security with proposed `TENANCY_KEY` is invaluable. In the end if people don't want to use `TENANCY_KEY` they can just not specify it in `.env` and it would be an empty string by default.

**Comment by luceos** [comment]
#739

**Pull request closed without merging**
