### PR TITLE
fix(queue): avoid make twice environment

### PR DESCRIPTION
**Pull request by HpiGuillaume**
Resolved issue: #728

### CODE REVIEW

**Comment by luceos** [comment]
Make resolves the ioc bound entity. If it's a singleton it won't be created twice. Not sure what your PR tries to solve, can you give some evidence of duplicate instantiation?

**Comment by HpiGuillaume** [comment]
@luceos I've add what I raise an error in the issue:
https://github.com/hyn/multi-tenant/issues/728

**Comment by luceos** [comment]
I'm not merging this until we get closure on what is happening. I hate to change code that seemingly changes nothing just to satisfy undetermined behaviour in one installation, sorry.

**Comment by HpiGuillaume** [comment]
I understand @luceos. 
I only wanted to help you :/

**Comment by luceos** [comment]
I understand and it's much appreciated. This is in no way a criticism towards your efforts, on the contrary it's my responsibility as a maintainer to guarantee quality and working code, as such I have to carefully review anything that comes into the package.

👏 keep it up though, considering contributing back and thinking over possible issues helps mature this package further!

**Pull request closed without merging**
